import Head from 'next/head';
import Link from 'next/link';
import styles from '../styles/Home.module.css';
import { sanityClient, urlFor } from '../lib/sanity';

const recipeQuery = `*[_type == "recipe"]{
  _id,
  name,
  slug,
  mainImage,
}`;

export default function Home({ recipes }) {
 console.log(recipes)
  return (
    <div className={styles.container}>
      <Head>
        <title>Chris's Kitchen</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Welcome to Chris's Kitchen</h1>

      <ul>
        {recipes?.length > 0 && recipes.map((recipe) => (
        <li>
          <Link key={recipe._id} href="/">
            <a>
              <img src={
                urlFor(recipe.mainImage).url()
                } />
              <span>{recipe.name}</span>
            </a>
          </Link>
        </li>
        ))}
      </ul>

    </div>
  )
}

export async function getStaticProps() {
 const recipes = await sanityClient.fetch(recipeQuery);
 return { props: { recipes }};
}